[package]
name = "redeye"
version = "0.1.0"
authors = ["Nick Pillitteri <nick@tshlabs.org>"]

[dependencies]
chrono = "0.4"
futures = "0.1"
failure = "0.1"
failure_derive = "0.1"
regex = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = "0.1"

[lib]
name = "redeye"
path = "src/redeye/lib.rs"
